---
- hosts: all
  become: true
  become_user: root
  tasks:
  - name: Update and upgrade apt packages
    become: true
    apt:
      update_cache: yes
      upgrade: yes
  - name: Install docker
    apt:
      name: docker
      state: latest
